app:
  github:
    timeout: ${GITHUB_REQUEST_TIMEOUT:10}
    api_url: "https://api.github.com"
    update-threshold: ${GITHUB_UPDATE_THRESHOLD:1}
  stackoverflow:
    timeout: ${STACKOVERFLOW_REQUEST_TIMEOUT:10}
    api-url: "https://api.stackexchange.com/2.3"

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${SCRAPPER_PORT:8081}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

bot:
  api:
    base-url: ${BOT_API_BASE_URL:http://localhost:8080}

scrapper:
  interval: ${SCRAPPER_INTERVAL:60000}
