app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${BOT_PORT}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

scrapper:
  api:
    base-url: ${SCRAPPER_API_BASE_URL}
